apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-frontend 
  namespace: argocd
spec:
  project: frontend-team

  source:
    repoURL: https://github.com/rajkumar25maurya/nginx-dep.git
    targetRevision: main
    path: frontend # Path to the directory containing the Kubernetes manifests (Deployment and Service)

  destination:
    server: https://192.168.1.140:6443 
    namespace: frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true